services:
  - type: web
    name: sistema-bancario
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sistema_bancario.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: sistema_bancario.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-bancario-db
          property: connectionString

databases:
  - name: sistema-bancario-db
    databaseName: sistema_bancario
    user: sistema_bancario_user 